kumuluzee:
  name: badmiton-app-matches-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/BadmintonAppUsersDS
      connection-url: jdbc:postgresql://database-1.ctekqcytce4y.eu-central-1.rds.amazonaws.com/badminton
      username: postgres
      password: postgres
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/BadmintonAppUsersDS
    metrics:
      web-instrumentation:
        - name: images-endpoint
          url-pattern: /v1/matches/*
rest-properties:
  maintenance-mode: false
